import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  UserOutline,
  MenuOutline,
  BlockOutline,
  ShoppingOutline,
  AuditOutline,
  PieChartOutline,
  IdcardOutline,
  BulbOutline,
  SettingOutline,
  BellOutline,
  PlusCircleOutline,
  SwapLeftOutline,
  SwapOutline,
  DownOutline,
  CloseCircleOutline,
  EyeInvisibleOutline,
  InfoCircleFill,
  ShopOutline,
  MedicineBoxOutline,
  PlusOutline,
  CommentOutline,
  ShoppingCartOutline,
  AlertOutline,
  EnvironmentOutline,
  CalendarOutline,
  LoadingOutline,
  FunnelPlotOutline,
  KeyOutline,
  TeamOutline,
  DoubleRightOutline,
  DoubleLeftOutline,
  PhoneOutline,
  MailOutline,
  CameraTwoTone,
  LogoutOutline,
  DollarOutline,
  TagOutline
} from '@ant-design/icons-angular/icons';

const icons = [
  UserOutline,
  MenuOutline,
  BlockOutline,
  ShoppingOutline,
  AuditOutline,
  PieChartOutline,
  IdcardOutline,
  BulbOutline,
  SettingOutline,
  BellOutline,
  PlusCircleOutline,
  SwapLeftOutline,
  SwapOutline,
  DownOutline,
  CloseCircleOutline,
  EyeInvisibleOutline,
  InfoCircleFill,
  ShopOutline,
  MedicineBoxOutline,
  PlusOutline,
  CommentOutline,
  ShoppingCartOutline,
  AlertOutline,
  EnvironmentOutline,
  CalendarOutline,
  LoadingOutline,
  FunnelPlotOutline,
  KeyOutline,
  TeamOutline,
  DoubleRightOutline,
  DoubleLeftOutline,
  PhoneOutline,
  MailOutline,
  CameraTwoTone,
  LogoutOutline,
  DollarOutline,
  TagOutline
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{ provide: NZ_ICONS, useValue: icons }]
})
export class IconsProviderModule {}
